In [1]:
import numpy as np
import matplotlib.pyplot as plt     

Matplotlib is building the font cache; this may take a moment.


In [2]:
#Data structure : [restaurant_id , 2021 , 2022 , 2023 , 2024 ]
sales_data = np.array ([
    [1 , 150000 , 180000 , 220000 , 250000],
    [2 , 120000 , 140000 , 160000 , 190000],
    [3 , 200000 , 130000 , 260000 , 300000],
    [4 , 180000 , 210000 , 240000 , 270000],
    [5 , 160000 , 185000 , 205000 , 230000]
])

In [11]:
print(np.shape(sales_data))
print("Sample data for first three row : \n" , sales_data[:3])
print("Sample data for first three row : \n" , sales_data[: , 1:])


(5, 5)
Sample data for first three row : 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 130000 260000 300000]]
Sample data for first three row : 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 130000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


Total sell of the year

In [ ]:
total_sell =    