In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3,4,5,6,7,8,9])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("1D array Slicing" , array1[2:8])
print("1D array Slicing" , array1[-3])
print("1D array Slicing" , array1[1:8:3])

1D array Slicing [3 4 5 6 7 8]
1D array Slicing 7
1D array Slicing [2 5 8]


In [4]:
print("Specific Element  : " , array2[1,2])
print("Entiere row : " , array2[1])
print("Entiere column : " , array2[:,2])


Specific Element  :  6
Entiere row :  [4 5 6]
Entiere column :  [3 6 9]


Shorting of the array 

In [5]:
unsorted = np.array([1,5,6,4,3,9,8,2,3,4,5])
print("Sorted array : ",np.sort(unsorted))

unsorted2d = np.array([[3,2,1],[8,6,5],[4,7,5]])
print("Sorted array : ",np.sort(unsorted2d)) 


Sorted array :  [1 2 3 3 4 4 5 5 6 8 9]
Sorted array :  [[1 2 3]
 [5 6 8]
 [4 5 7]]


Filtering the array 

In [6]:
unsorted = np.array([1,5,6,4,3,9,8,2,3,4,5])
print("Sorted array : ",np.sort(unsorted))

arr1d = np.array([1,5,6,4,3,9,8,2,3,4,5])
even = arr1d[arr1d%2==0] 
print("Array : ",even)


Sorted array :  [1 2 3 3 4 4 5 5 6 8 9]
Array :  [6 4 8 2 4]


Adding and Removing 

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

sum = arr1+arr2
print(sum)

combine = np.concatenate((arr1,arr2))
print(combine)

[5 7 9]
[1 2 3 4 5 6]


Array Compatibility

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility check : " , a.shape == b.shape)

Compatibility check :  True


In [11]:
original = np.array([[1,2],[3,4]])
new_array = np.array([[5,6]])

with_new_row = np.vstack((original,new_array))
print("Origional : ",original)
print("\nNew row : ",new_array)
print("\nUpdated array : ",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("\nUpdated array : ",with_new_col)



Origional :  [[1 2]
 [3 4]]

New row :  [[5 6]]

Updated array :  [[1 2]
 [3 4]
 [5 6]]

Updated array :  [[1 2 7]
 [3 4 8]]
