# Phase 1

In [5]:
import numpy as np

creating array from list 

In [6]:
array1d = np.array([1,2.3,4,5])
print("1D array :",array1d)

array2d = np.array([[1,2,3],[4,5,6]])
print("2D Array :",array2d)


1D array : [1.  2.3 4.  5. ]
2D Array : [[1 2 3]
 [4 5 6]]


In [7]:
list1 = [1,2,3]
print("Multiplication of the list : ", list1 * 2) # whole list quantity multiply 

np_array = np.array([1,2,3])
print("Multiplication of the arraya : ", np_array * 2) # multiply by the element 


Multiplication of the list :  [1, 2, 3, 1, 2, 3]
Multiplication of the arraya :  [2 4 6]


In [13]:
import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("Calculation time of the list is : ",time.time()-start)

start = time.time()
np_array = np.arange(100000000)*2
print("Calculation time of the list is : ",time.time()-start)

Calculation time of the list is :  5.755001783370972
Calculation time of the list is :  0.3627204895019531


Creating the array form the scratch 


In [15]:
zero = np.zeros((3,4))
print("Zero valued array :\n",zero)

Zero valued array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
one = np.ones((3,4))
full = np.full((2,2),36.5)
random = np.random.random((3,4))
sequance = np.arange(0 , 50 , 5)

print("\nOnes array :",one)
print("\nFull array :",full)
print("\nRandom array :",random)
print("\nSequance array :",sequance)


Ones array : [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full array : [[36.5 36.5]
 [36.5 36.5]]

Random array : [[0.31277125 0.66423371 0.24871799 0.19588929]
 [0.80223561 0.44735935 0.89362268 0.02017162]
 [0.77604005 0.34839957 0.04020121 0.3102533 ]]

Sequance array : [ 0  5 10 15 20 25 30 35 40 45]


In [20]:
vector = np.array([1,2,3])
print("Vector : " , vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Vector : " , matrix)

tensor = np.array([[1,2],[2,3],[3,4],[4,5]])
print("Vector : " , tensor)


Vector :  [1 2 3]
Vector :  [[1 2 3]
 [4 5 6]]
Vector :  [[1 2]
 [2 3]
 [3 4]
 [4 5]]


Array properties